export const data = {
  hotCrossBuns: [
    ["orange", "", "pink", ""],
    ["green", "", "", ""],
    ["orange", "", "pink", ""],
    ["green", "", "", ""],
    ["green", "green", "green", "green"],
    ["pink", "pink", "pink", "pink"],
    ["orange", "", "pink", ""],
    ["green", "", "", ""],
  ],
  rollingAlong: [
    ["orange", "pink", "green", "pink"],
    ["orange", "orange", "orange", ""],
    ["pink", "pink", "pink", ""],
    ["orange", "orange", "orange", ""],
    ["orange", "pink", "green", "pink"],
    ["orange", "orange", "orange", "orange"],
    ["pink", "pink", "orange", "pink"],
    ["green", "", "", ""],
  ],
  twinkleTwinkle: [
    ["green", "green", "yellow", "yellow"],
    ["blue", "blue", "yellow", ""],
    ["purple", "purple", "orange", "orange"],
    ["pink", "pink", "green", ""],
    ["yellow", "yellow", "purple", "purple"],
    ["orange", "orange", "pink", ""],
    ["yellow", "yellow", "purple", "purple"],
    ["orange", "orange", "pink", ""],
    ["green", "green", "yellow", "yellow"],
    ["blue", "blue", "yellow", ""],
    ["purple", "purple", "orange", "orange"],
    ["pink", "pink", "green", ""],
  ],
  frereJacques: [
    ["green", "", "pink", "", "orange", "", "green", ""],
    ["green", "", "pink", "", "orange", "", "green", ""],
    ["orange", "", "purple", "", "yellow", "", "", ""],
    ["orange", "", "purple", "", "yellow", "", "", ""],
    ["yellow", "blue", "yellow", "purple", "orange", "", "green", ""],
    ["yellow", "blue", "yellow", "purple", "orange", "", "green", ""],
    ["green", "", "yellow", "", "green", "", "", ""],
    ["green", "", "yellow", "", "green", "", "", ""],
  ],
  odeToJoy: [
    ["orange", "orange", "purple", "yellow"],
    ["yellow", "purple", "orange", "pink"],
    ["green", "green", "pink", "orange"],
    ["orange", "pink", "pink", ""],
    ["orange", "orange", "purple", "yellow"],
    ["yellow", "purple", "orange", "pink"],
    ["green", "green", "pink", "orange"],
    ["pink", "green", "green", ""],
  ],
}
